title: Support Cours & TD
#description:
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Romain Chatillon
repo_url: https://github.com/sthibaul/sthibaul.github.io
#repo_url: "https://github.com/carlosperate/jekyll-theme-rtd"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist
